### PR TITLE
Implement embedded-io traits for Usart

### PR DESCRIPTION
**Pull request by akhilles**
This is gated by the embedded-hal feature. Tested on an STM32H747.

### CODE REVIEW

**Comment by David-OConnor** [comment]
Looking good; I'll test it at some point.

**Comment by David-OConnor** [comment]
Is this ready for revie?

**Comment by akhilles** [comment]
Yup, good to review

**Comment by akhilles** [comment]
Discovered an issue with more testing where error states weren't being cleared reliably. Turns out on newer families you have to explicitly clear error states from the ICR register. Fixed in https://github.com/David-OConnor/stm32-hal/pull/111/commits/ec26a71f45acf22f0c04e3e43f9d8af990dff6c9. I've been testing quite a bit on the H7, but not other families.

**Pull request merged**
