### PR TITLE
Removed erroneous h7 cfg line in adc.rs which was preventing all adc …

### PR DESCRIPTION
**Pull request by Kaikallon**
Removed erroneous h7 cfg line in adc.rs which was preventing all adc functionality on the g4 series.

I'm a beginner when it comes to rust, but it seems like this is correct. Please feedback if I'm wrong.

### CODE REVIEW

**Comment by David-OConnor** [comment]
From the G4 Reference manual (RM044), here's the documentation for the register. Additionally, it compiles for all G4 targets on my end.

> 3 EOS: End of regular sequence flag
This bit is set by hardware at the end of the conversions of a regular sequence of channels. It is 
cleared by software writing 1 to it.
0: Regular Conversions sequence not complete (or the flag event was already acknowledged and 
cleared by software)
1: Regular Conversions sequence complete

What G4 variant are you compiling for, and what error are you getting? Thank you.

**Comment by Kaikallon** [comment]
Compiling for the G431. The error is that all of the ADC stuff is missing if that line is there because (correct me if I'm wrong) the line that I removed demands that and H7 be used for the G431 stuff to work. That was at least how it seems to me. 

I'm sorry about the following two commits. I didn't know that those would be included in the pull request. This is the first time I'm contributing using pull requests and github. I do think that they are correct though, but I didn't mean to include them in this.

**Comment by David-OConnor** [comment]
#1: Could you please post exactly what features you're compiling with? I'm unable to replicate this with `features = "g431 g4rt"`

#2: Which part don't you believe applies to G4? For the interrupt change you made, I posted the RM quote. Here's the section to find the quote for the other change you made (Sample time): `21.6.7 - ADC sample time register 2 `. Which part do you think is H7 only?

**Comment by David-OConnor** [comment]
Ah, I see! The cfg line at the end. Good changes all around. Merging.

**Pull request merged**
