### PR TITLE
Feature gate TIM15 and TIM16

### LINKED ISSUE #6: Feature gate more of the timer peripherals
I decided to look into introducing F4 support.

the F4 does not have `TIM15`,`TIM16`. FEature gating will be necessary for `src.timer.rs`'s include on line 9.

The DAC has a different name, but feature gating exists here so that can be addressed directly.

### PR DESCRIPTION
**Pull request by theunkn0wn1**
resolves #6

### CODE REVIEW

**Comment by David-OConnor** [comment]
`#[cfg(not(feature = "f446"))]`

**Comment by theunkn0wn1** [comment]
> `#[cfg(not(feature = "f446"))]`

yeah That would require me doing this work in #7 .
Would you prefer i roll this into #7 ?

**Comment by David-OConnor** [comment]
Might as well add your `Cargo.toml` changes here from the other PR too

**Comment by theunkn0wn1** [comment]
Wilco.

**Comment by theunkn0wn1** [comment]
Cherry picked only the `Cargo.toml` and `lib.rs` changes; the crate won't compile with the F446 feature without #7 but should still build for everything else. 

Applied the much cleaner feature gate as suggested.

**Comment by David-OConnor** [comment]
Sweet

**Pull request merged**
