### PR TITLE
F4 support

### PR DESCRIPTION
**Pull request by theunkn0wn1**
This PR is currently a DRAFT as it is incomplete.

This PR adds support for the `stm32f446`.

blocked by #6

### CODE REVIEW

**Comment by David-OConnor** [comment]
Great. I suspect F4 won't be tough to patch in. I mainly focused on newer ones, (F3 since I have a current project with it that uses many periphs, so can ops test), but at the time expect the multi-family aspect to be tougher than it's been so far.

**Comment by theunkn0wn1** [comment]
The F4 is of specific interest to me since that is what I have on hand and am using in my projects.
I am hesitant to PR new features to this HAL without being able to manually verify that they work correctly at least on one MCU.

**Comment by David-OConnor** [comment]
I completely agree with that approach - ops testing on hardware is more valuable metric as far as I'm concerned.

**Comment by David-OConnor** [comment]
At a glance, clock config looks similar to F3. Can probably expand a feature-gated version if the F3 clocks module instead of making a new one.

**Comment by theunkn0wn1** [comment]
> At a glance, clock config looks similar to F3. Can probably expand a feature-gated version of the F3 clocks module instead of making a new one.

Interesting, will investigate once I get there.
Presently preparing a patch for #6 then Seeing if i can resolve the remaining build failures in `src/timer.rs`.
Afterwards I will look at the clock configs.

**Comment by theunkn0wn1** [comment]
(Force pushes to synchronize with main.)

**Comment by theunkn0wn1** [comment]
Ok. This clock stuff has me rather confused.
It appears the F3 and the F4 use different notations.
In the F3's reference manual (using RM0316) this `PLLMUL` register exists to define the PLL multiplication factor, and only has 4 bits in it. 
I cannot find the same register in the F4's RM0390. The closest I can find is this `PLLN` register which is described to do the same thing(?), which is 8 bits wide.

**Comment by David-OConnor** [comment]
Hey I'm on my phone now. You're right - that stuff is different. The good news is that part may be the main diff between the 2

**Comment by David-OConnor** [comment]
Latest branch has mostly-working F4. See Errata at the bottom of the readme for things you could work on. (Ie I2C, low power modes, and adding more timers)

**Comment by David-OConnor** [comment]
I2C and low power done.

**Comment by theunkn0wn1** [comment]
Looks Like you got to this well before I had time to finish what I started.
I don't think there is anything in this PR that is usable and It appears the F4 has support in master already.

I will close this now as redundant.

**Pull request closed without merging**
