### PR TITLE
fix compile on stm32l4

### PR DESCRIPTION
**Pull request by gfabiano**
To compile my project I had to modify this line. I don't know what was used for.

I was thinking if it is better to update this library to cover the new bxcan 0.6 that have a clearer interface.

### CODE REVIEW

**Comment by David-OConnor** [comment]
Good catch - that was an error from before a refactor. I agree on updating to the new bxcan, now that it's available.

**Comment by David-OConnor** [comment]
Updated to 0.6. Seems like there are breaking changes for user code, but not sure if there are any changes we need to impl here. LMK if it's working.

**Comment by gfabiano** [comment]
> Updated to 0.6. Seems like there are breaking changes for user code, but not sure if there are any changes we need to impl here. LMK if it's working.

I modified the code with the needed changes to config with 0.6 but it get stuck on transmission and I don't receive messages. I had the same problem before with 0.5 but was a clock misconfiguration on abp1, now IDK

```rust
         let mut clock_cfg = Clocks::default();
         clock_cfg.input_src = InputSrc::Pll(PllSrc::Hsi);
         clock_cfg.setup().unwrap();
 
         defmt::info!("sysclock: {:?}, apb1: {:?}",
             clock_cfg.sysclk(),
             clock_cfg.apb1()
         );

         defmt::info!("CAN init");
 
         let mut can = {
             let mut _rx = Pin::new(Port::A, 11, PinMode::Alt(9));
             let mut _tx = Pin::new(Port::A, 12, PinMode::Alt(9));
 
             _rx.output_type(OutputType::PushPull);
             _tx.output_type(OutputType::PushPull);
             let can = Can::new(dp.CAN1, &mut rcc);
 
             bxcan::Can::builder(can)
                 // APB1 (PCLK1): 80MHz, Bit rate: 1000kBit/s, Sample Point 87.5%
                 // Value was calculated with http://www.bittiming.can-wiki.info/
                 .set_bit_timing(0x001c_0004)
                 .enable()
         };
 
         // Configure filters so that can frames can be received.
         let mut filters = can.modify_filters();
         filters.enable_bank(0, Mask32::accept_all());
 
         // Drop filters to leave filter configuraiton mode.
         drop(filters);
 
         // Send a frame
         let mut test: [u8; 8] = [0; 8];
         let id: u16 = 0x500;
 
         test[0] = 72;
         test[1] = 1;
         test[2] = 2;
         test[3] = 3;
         test[4] = 4;
         test[5] = 5;
         test[6] = 6;
         test[7] = 7;
         let test_frame = Frame::new_data(StandardId::new(id).unwrap(), test);
         can.transmit(&test_frame).unwrap();
 
         // Wait for TX to finish
         while !can.is_transmitter_idle() {}
```

Before it was like that, this is the only part I changed

```rust
        let mut can = {
             let mut _rx = Pin::new(Port::A, 11, PinMode::Alt(9));
             let mut _tx = Pin::new(Port::A, 12, PinMode::Alt(9));
 
             _rx.output_type(OutputType::PushPull);
             _tx.output_type(OutputType::PushPull);
 
 
             let can = Can::new(dp.CAN1, &mut rcc);
 
             bxcan::Can::new(can)
         };
         can.configure(|config| {
             // APB1 (PCLK1): 80 MHz, Bit rate: 1000kBit/s, Sample Point 87.5%
             // Value was calculated with http://www.bittiming.can-wiki.info/
             config.set_bit_timing(0x001c_0004);
         });

         while let Err(_) = can.enable() {}
```

**Comment by David-OConnor** [comment]
Any luck? Regrettably, I've never used CAN. Is there anything I need to change on the `bxCan` wrapper here to work with 0.6? Could it be a memory location thing?

**Comment by gfabiano** [comment]
Yes, sorry for the late reply, at the time my computer was broken. I confirm that it works, my micro misconfigured. I also made a fix for the actual version because of the change on feature name (can to bx_can). 

In these days I can make also a tested example of use.

**Pull request merged**
